# Generated by Django 5.2.1 on 2025-10-29 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LegacyGameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.PositiveIntegerField(verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('start_time', models.DateTimeField(verbose_name='Début')),
                ('end_time', models.DateTimeField(verbose_name='Fin')),
                ('verdict', models.CharField(max_length=50, verbose_name='Verdict')),
                ('map_name', models.CharField(max_length=100, verbose_name='Nom de la map')),
            ],
        ),
        migrations.CreateModel(
            name='LegacyGameSessionPlayerRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_id', models.PositiveIntegerField(verbose_name='ID de la ligne')),
                ('player_id', models.PositiveIntegerField(verbose_name='ID du joueur')),
                ('gamesession_id', models.PositiveIntegerField(verbose_name='ID de la GameSession')),
                ('role_id', models.PositiveIntegerField(verbose_name='ID du rôle')),
                ('status', models.CharField(max_length=50, verbose_name='Statut')),
            ],
        ),
        migrations.CreateModel(
            name='LegacyImportError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(max_length=255)),
                ('error_message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LegacyMapNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_name', models.CharField(max_length=100, verbose_name='Code name')),
                ('display_name', models.CharField(max_length=255, verbose_name='Display name')),
                ('game_session_names', models.JSONField(blank=True, default=list, verbose_name='Game session names')),
            ],
        ),
        migrations.CreateModel(
            name='LegacyPlayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID du joueur (CSV)')),
                ('name', models.CharField(max_length=255, verbose_name='Nom du joueur')),
                ('created_at', models.DateTimeField(verbose_name='Date de création')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='Données brutes du CSV')),
            ],
        ),
        migrations.CreateModel(
            name='LegacyRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.PositiveIntegerField(verbose_name='ID du rôle')),
                ('name', models.CharField(max_length=255, verbose_name='Nom du rôle')),
            ],
        ),
        migrations.CreateModel(
            name='MapName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_name', models.CharField(max_length=100, unique=True, verbose_name='Nom de la carte (code)')),
                ('display_name', models.CharField(max_length=255, verbose_name='Nom affiché')),
            ],
        ),
        migrations.CreateModel(
            name='LegacyMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('authors', models.CharField(blank=True, default='', max_length=255, verbose_name='Auteurs')),
                ('min_players', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre de joueurs minimum')),
                ('max_players', models.PositiveIntegerField(verbose_name='Nombre de joueurs maximum')),
                ('type', models.CharField(max_length=16, verbose_name='Type')),
                ('pbo_file', models.FileField(upload_to='legacy_missions/', verbose_name='Fichier de mission (.pbo)')),
                ('version', models.CharField(max_length=50, verbose_name='Version')),
                ('map', models.CharField(max_length=100, verbose_name='Map')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name="Date d'upload")),
                ('onLoadMission', models.TextField(blank=True, default='', verbose_name="onLoadMission (texte écran de chargement, sous l'image)")),
                ('overviewText', models.TextField(blank=True, default='', verbose_name='overviewText (texte page de lobby)')),
                ('loadScreen', models.ImageField(blank=True, null=True, upload_to='legacy_missions/', verbose_name='loadScreen (image écran de chargement)')),
                ('briefing', models.JSONField(blank=True, default=list, null=True, verbose_name='Briefing (éléments extraits du fichier briefing.sqf)')),
                ('briefing_images', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(blank=True, default='', max_length=20, verbose_name='Statut de la mission')),
                ('linkedUser', models.CharField(blank=True, default='', max_length=255, verbose_name='Utilisateur lié')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_missions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur propriétaire')),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('authors', models.CharField(max_length=255, verbose_name='Auteurs')),
                ('min_players', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre de joueurs minimum')),
                ('max_players', models.PositiveIntegerField(verbose_name='Nombre de joueurs maximum')),
                ('type', models.CharField(choices=[('CO', 'COOP'), ('TVT', 'TvT'), ('GM', 'GM'), ('HC', 'HiCom'), ('TRAINING', 'Training'), ('COM', 'COM')], max_length=16, verbose_name='Type')),
                ('version', models.CharField(max_length=50, verbose_name='Version')),
                ('map', models.CharField(max_length=100, verbose_name='Map')),
                ('publication_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de publication')),
                ('onLoadMission', models.TextField(blank=True, default='Non renseigné', verbose_name="onLoadMission (texte écran de chargement, sous l'image)")),
                ('overviewText', models.TextField(blank=True, default='Non renseigné', verbose_name='overviewText (texte page de lobby)')),
                ('loadScreen', models.ImageField(blank=True, null=True, upload_to='missions/', verbose_name='loadScreen (image écran de chargement)')),
                ('briefing', models.JSONField(blank=True, default=list, null=True, verbose_name='Briefing (éléments extraits du fichier briefing.sqf)')),
                ('briefing_images', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('JOUABLE', 'Jouable'), ('NON_JOUABLE', 'Non jouable'), ('INCONNU', 'Inconnu'), ('SUPPRIMEE', 'Supprimée')], default='JOUABLE', max_length=20, verbose_name='Statut de la mission')),
                ('last_status_update', models.DateTimeField(blank=True, null=True, verbose_name='Dernier changement de statut')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur propriétaire')),
            ],
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom de la mission')),
                ('map', models.CharField(max_length=100, verbose_name='Carte')),
                ('version', models.CharField(max_length=50, verbose_name='Version de la mission')),
                ('start_time', models.DateTimeField(verbose_name='Début de la mission')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Fin de la mission')),
                ('verdict', models.CharField(choices=[('INCONNU', 'Inconnu'), ('@EFFACER', '@Effacer'), ('SUCCES', 'Succès'), ('ECHEC', 'Echec'), ('PvP', 'PvP'), ('TRAINING', 'Training')], default='INCONNU', max_length=16, verbose_name='Verdict de la session')),
                ('mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_sessions', to='gdc_storm.mission')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom du joueur')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('users', models.ManyToManyField(blank=True, related_name='players', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateurs liés')),
            ],
        ),
        migrations.CreateModel(
            name='GameSessionPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('VIVANT', 'Vivant'), ('MORT', 'Mort')], default='VIVANT', max_length=10)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='gdc_storm.gamesession')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to='gdc_storm.player')),
            ],
        ),
    ]
