# Generated by Django 5.2.1 on 2025-10-29 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdc_storm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='created_at',
            field=models.DateTimeField(verbose_name='Date de création'),
        ),
    ]
